# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fcebcf99819a5abc66c7b5f406f373ebc36e3be18dc030bf9810d96d95a0722bb50b49b2de0fa424554e9e9f68fbcbc7eb76de7bb100c58b91fd89e7b7a85fb

test:
  secret_key_base: d53751524e893bd6418276870b1dafa1f2e4c633b8bed7ea12134368092b109980967d986db19b92ca6c5cb6adf4990c8f27ed68e2fa1903a46b00813252c8db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
