# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e43a492372a0cd97538ddd0027e7463ee8663494d7c425dfa011796247d6d8f7da70baea6c2a81e6ae970e5b33f28758946b974800694129cd4184dd723c2e87

test:
  secret_key_base: 7d69a180f74fc620cf13e8ab20d591dd092206c166e559079ccc5ab5094452fd152a102723d299d29ec464d2b331e338faac99309aea727539f0433c2d2b9277

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
